"""
Transpiler for Aster.

Converts a parsed and semantically-analysed program into target-language
source code.  Supported targets: ``python``, ``rust``, ``javascript``,
and ``neural`` (a symbolic neural-pipeline notation).

Usage::

    from language.parser.tokenizer import Tokenizer
    from language.parser.parser import Parser
    from compiler.transpiler import Transpiler

    tokens = Tokenizer(source).tokenize()
    program = Parser(tokens).parse()

    transpiler = Transpiler()
    print(transpiler.to_python(program))
    print(transpiler.to_rust(program))
    print(transpiler.to_javascript(program))
    print(transpiler.to_neural(program))
"""

from __future__ import annotations

from typing import List

from language.parser.ast_builder import (
    ActionCall,
    ActionDecl,
    CycleDecl,
    EntityDecl,
    Node,
    Program,
)


class TranspileError(Exception):
    """Raised when transpilation cannot proceed."""


class Transpiler:
    """
    Multi-target code generator for .co programs.

    Each ``to_*`` method accepts a :class:`~language.parser.ast_builder.Program`
    and returns a string of target-language source code.
    """

    # ------------------------------------------------------------------
    # Python
    # ------------------------------------------------------------------

    def to_python(self, program: Program) -> str:
        lines: List[str] = [
            "# Generated by Aster transpiler",
            "",
        ]

        # Collect entities as variables initialised to None
        for stmt in program.statements:
            if isinstance(stmt, EntityDecl):
                lines.append(f"{stmt.name} = None")
        lines.append("")

        # Emit action definitions
        for stmt in program.statements:
            if isinstance(stmt, ActionDecl):
                src = stmt.relation.source
                tgt = stmt.relation.target
                lines.append(f"def {stmt.name}({src}, {tgt}):")
                lines.append(f'    """Action: {src} -> {tgt}"""')
                lines.append(f"    return {tgt}")
                lines.append("")

        # Emit cycle runners
        for stmt in program.statements:
            if isinstance(stmt, CycleDecl):
                lines.append(f"def cycle_{stmt.name}():")
                lines.append(f'    """Cycle: {stmt.name}"""')
                for step in stmt.body:
                    if isinstance(step, ActionCall):
                        lines.append(f"    {step.name}({step.name}, {step.name})")
                lines.append("")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Rust
    # ------------------------------------------------------------------

    def to_rust(self, program: Program) -> str:
        lines: List[str] = [
            "// Generated by Aster transpiler",
            "",
        ]

        for stmt in program.statements:
            if isinstance(stmt, ActionDecl):
                src = stmt.relation.source
                tgt = stmt.relation.target
                fn_name = stmt.name.replace("-", "_")
                lines.append(f"fn {fn_name}({src}: &dyn std::any::Any, {tgt}: &mut dyn std::any::Any) {{")
                lines.append(f"    // Action: {src} -> {tgt}")
                lines.append("}")
                lines.append("")

        for stmt in program.statements:
            if isinstance(stmt, CycleDecl):
                fn_name = f"cycle_{stmt.name}".replace("-", "_")
                lines.append(f"fn {fn_name}() {{")
                for step in stmt.body:
                    if isinstance(step, ActionCall):
                        call_name = step.name.replace("-", "_")
                        lines.append(f"    // {call_name}(...);")
                lines.append("}")
                lines.append("")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # JavaScript
    # ------------------------------------------------------------------

    def to_javascript(self, program: Program) -> str:
        lines: List[str] = [
            "// Generated by Aster transpiler",
            "",
        ]

        for stmt in program.statements:
            if isinstance(stmt, ActionDecl):
                src = stmt.relation.source
                tgt = stmt.relation.target
                lines.append(f"function {stmt.name}({src}, {tgt}) {{")
                lines.append(f"  // Action: {src} -> {tgt}")
                lines.append(f"  return {tgt};")
                lines.append("}")
                lines.append("")

        for stmt in program.statements:
            if isinstance(stmt, CycleDecl):
                lines.append(f"function cycle_{stmt.name}() {{")
                for step in stmt.body:
                    if isinstance(step, ActionCall):
                        lines.append(f"  {step.name}();")
                lines.append("}")
                lines.append("")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Neural pipeline notation
    # ------------------------------------------------------------------

    def to_neural(self, program: Program) -> str:
        """
        Produce a symbolic neural-pipeline notation where each action
        becomes a directed transformation layer.

        Example output::

            dataset -> training_layer -> model
            model -> evaluation_layer -> metrics
        """
        lines: List[str] = [
            "# Neural pipeline — generated by Aster transpiler",
            "",
        ]

        for stmt in program.statements:
            if isinstance(stmt, ActionDecl):
                src = stmt.relation.source
                tgt = stmt.relation.target
                layer = f"{stmt.name}_layer"
                lines.append(f"{src} -> {layer} -> {tgt}")

        return "\n".join(lines)
